name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pycodestyle poetry
        poetry install
    - name: pycodestyle
      run: pycodestyle --max-line-length=200 pdfmerge
    - name: Build test
      run: poetry build
    - name: test
      run: |
        poetry run pdfmerge --input-dir example --out example/merged-pdf
